export const productDetail = [
  {
    id: "1",
    title: "Monitor LG LED 19'' 19M38A-B VGA",
    price: 31730,
    img01: "../../assets/monitor01.webp",
    img02: "../../assets/monitor01perfil.webp",
    img03: "../../assets/monitor01detras.webp",
    stock: 5,
  },
  {
    id: "2",
    title: "Monitor LG 22 MK600M IPS Full HD Bordes Ultra Finos",
    price: 47990,
    img01: "../../assets/monitor02.webp",
    img02: "../../assets/monitor02-perfil.webp",
    img03: "../../assets/monitor02-atras.webp",
    stock: 5,
  },
  {
    id: "3",
    title: "Monitor Samsung FLAT 27 4K S70A Series",
    price: 98900,
    img01: "../../assets/monitor03.webp",
    img02: "../../assets/monitor03-perfil.webp",
    img03: "../../assets/monitor03-atras.webp",
    stock: 5,
  },
  {
    id: "4",
    title: "Gabinete Cougar Gemini M Iron Gray",
    price: 13680,
    img01: "../../assets/gabinete01.webp",
    img02: "../../assets/gabinete01-perfil.webp",
    img03: "../../assets/gabinete01-frente.webp",
    stock: 5,
  },
  {
    id: "5",
    title: "Gabinete ASUS TUF GT301 ARGB Vidrio Templado",
    price: 21870,
    img01: "../../assets/gabinete02.webp",
    img02: "../../assets/gabinete02-perfil.webp",
    img03: "../../assets/gabinete02-frente.webp",
    stock: 5,
  },
  {
    id: "6",
    title: "Gabinete Corsair 7000X ICUE Vidrio Templado White RGB Full Tower",
    price: 73610,
    img01: "../../assets/gabinete03.webp",
    img02: "../../assets/gabinete03-perfil.webp",
    img03: "../../assets/gabinete03-frente.webp",
    stock: 5,
  },
  {
    id: "7",
    title: "Teclado Mecanico Redragon SHRAPNEL K589 RGB Switch Blue ESP",
    price: 8800,
    img01: "../../assets/teclado01.webp",
    img02: "../../assets/teclado01-frente.webp",
    img03: "../../assets/teclado01-perfil.webp",
    stock: 5,
  },
  {
    id: "8",
    title: "Teclado Mecanico Cooler Master CK530 RGB Red Switch US ",
    price: 13262,
    img01: "../../assets/teclado02.webp",
    img02: "../../assets/teclado02-frente.webp",
    img03: "../../assets/teclado02-perfil.webp",
    stock: 5,
  },
  {
    id: "9",
    title: "Teclado Mecanico ASUS ROG STRIX Scope TKL RGB Cherry MX Brown",
    price: 20590,
    img01: "../../assets/teclado03.webp",
    img02: "../../assets/teclado03-frente.webp",
    img03: "../../assets/teclado03-perfil.webp",
    stock: 5,
  },
  {
    id: "10",
    title: "Mouse Glorious Model D Minus - Matte Black",
    price: 7155,
    img01: "../../assets/mouse01.webp",
    img02: "../../assets/mouse01-frente.webp",
    img03: "../../assets/mouse01-perfil.webp",
    stock: 5,
  },
  {
    id: "11",
    title: "Mouse Logitech G502 Gaming Hero High Performance RGB",
    price: 9000,
    img01: "../../assets/mouse02.webp",
    img02: "../../assets/mouse02-frente.webp",
    img03: "../../assets/mouse02-perfil.webp",
    stock: 5,
  },
  {
    id: "12",
    title: "Mouse ASUS P511 ROG CHAKRAM Core USB RGB 16K DPI",
    price: 14010,
    img01: "../../assets/mouse03.webp",
    img02: "../../assets/mouse03-frente.webp",
    img03: "../../assets/mouse03-perfil.webp",
    stock: 5,
  },
];
