export const productos = [
  {
    id: "1",
    title: "Monitor",
    price: 31730,
    img: "../../assets/monitor01.webp",
    stock: 5,
    category:"monitor",
  },
  {
    id: "2",
    title: "Monitor",
    price: 47990,
    img: "../../assets/monitor02.webp",
    stock: 5,
    category:"monitor",
  },
  {
    id: "3",
    title: "Monitor",
    price: 98900,
    img: "../../assets/monitor03.webp",
    stock: 5,
    category:"monitor",
  },
  {
    id: "4",
    title: "Gabinete",
    price: 16700,
    img: "../../assets/gabinete01.webp",
    stock: 5,
    category:"gabinete",
  },
  {
    id: "5",
    title: "Gabinete",
    price: 20420,
    img: "../../assets/gabinete02.webp",
    stock: 5,
    category:"gabinete",
  },
  {
    id: "6",
    title: "Gabinete",
    price: 73610,
    img: "../../assets/gabinete03.webp",
    stock: 5,
    category:"gabinete",
  },
  {
    id: "7",
    title: "Teclado",
    price: 8100,
    img: "../../assets/teclado01.webp",
    stock: 5,
    category:"teclado",
  },
  {
    id: "8",
    title: "Teclado",
    price: 13900,
    img: "../../assets/teclado02.webp",
    stock: 5,
    category:"teclado",
  },
  {
    id: "9",
    title: "Teclado",
    price: 21000,
    img: "../../assets/teclado03.webp",
    stock: 5,
    category:"teclado",
  },
  {
    id: "10",
    title: "Mouse",
    price: 7670,
    img: "../../assets/mouse01.webp",
    stock: 5,
    category:"mouse",
  },
  {
    id: "11",
    title: "Mouse",
    price: 5400,
    img: "../../assets/mouse02.webp",
    stock: 5,
    category:"mouse",
  },
  {
    id: "12",
    title: "Mouse",
    price: 13870,
    img: "../../assets/mouse03.webp",
    stock: 5,
    category:"mouse",
  },
];
